// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advanced.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTags = `-- name: AddPostTags :exec
UPDATE posts
SET tags = array_cat(tags, $1::text[])
WHERE id = $2::uuid
`

type AddPostTagsParams struct {
	NewTags []string
	ID      pgtype.UUID
}

// text[] 列に要素を追加する (array_cat)
// Go 側の引数 new_tags は []string になる (pgx/v5 + emit_empty_slices)
func (q *Queries) AddPostTags(ctx context.Context, arg AddPostTagsParams) error {
	_, err := q.db.Exec(ctx, addPostTags, arg.NewTags, arg.ID)
	return err
}

const getAuthorMetadata = `-- name: GetAuthorMetadata :one
SELECT metadata FROM authors WHERE id = $1
`

// jsonb カラムを読み返して []byte として受け取る
func (q *Queries) GetAuthorMetadata(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAuthorMetadata, id)
	var metadata []byte
	err := row.Scan(&metadata)
	return metadata, err
}

const getPostTags = `-- name: GetPostTags :one
SELECT tags FROM posts WHERE id = $1
`

// text[] を []string として受け取る
func (q *Queries) GetPostTags(ctx context.Context, id pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getPostTags, id)
	var tags []string
	err := row.Scan(&tags)
	return tags, err
}

const keysetListPosts = `-- name: KeysetListPosts :many
WITH anchor AS (
    SELECT created_at, id
    FROM posts
    WHERE id = $1::uuid
)
SELECT p.id, p.author_id, p.title, p.body, p.tags, p.status, p.published_at, p.created_at FROM posts p
WHERE
    $1::uuid IS NULL
    OR (p.created_at, p.id) < (SELECT created_at, id FROM anchor)
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2::bigint
`

type KeysetListPostsParams struct {
	CursorID pgtype.UUID
	PageSize int64
}

// CTE を使った keyset ページネーション
// cursor_id が NULL の場合は先頭ページ、指定した場合はその投稿の次ページを返す
// インデックス idx_posts_keyset (created_at DESC, id DESC) を活用する
func (q *Queries) KeysetListPosts(ctx context.Context, arg KeysetListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, keysetListPosts, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, author_id, title, body, tags, status, published_at, created_at FROM posts WHERE status = 'published' ORDER BY created_at DESC
`

// PostStatus 型の定数 (PostStatusPublished 等) を使う例
func (q *Queries) ListPublishedPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAuthorMetadata = `-- name: UpsertAuthorMetadata :exec

UPDATE authors
SET metadata = $1::jsonb
WHERE id = $2::uuid
`

type UpsertAuthorMetadataParams struct {
	Metadata []byte
	ID       pgtype.UUID
}

// 06-advanced で使用するクエリ
// 示す機能: JSONB / text[] 配列 / CTE + keyset ページネーション / enum 値
// jsonb 列に []byte (JSON) を渡す
// sqlcgen 側の型: []byte (pgx/v5 のデフォルト)
func (q *Queries) UpsertAuthorMetadata(ctx context.Context, arg UpsertAuthorMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertAuthorMetadata, arg.Metadata, arg.ID)
	return err
}
