// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authors.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one

INSERT INTO authors (name, bio, metadata)
VALUES ($1, $2, $3)
RETURNING id, name, bio, metadata, created_at
`

type CreateAuthorParams struct {
	Name     string
	Bio      string
	Metadata []byte
}

// 01-basics で使用するクエリ
// 示す機能: :one / :many / :exec / :execrows
// INSERT ... RETURNING * → Author 構造体を返す (:one)
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio, arg.Metadata)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :execrows
DELETE FROM authors WHERE id = $1
`

// :execrows は影響を受けた行数を int64 で返す
// 例: 0 なら対象なし、1 なら削除成功
func (q *Queries) DeleteAuthor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio, metadata, created_at FROM authors WHERE id = $1
`

// 主キーで1行取得 (:one は存在しない場合 pgx.ErrNoRows を返す)
func (q *Queries) GetAuthor(ctx context.Context, id pgtype.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, metadata, created_at FROM authors ORDER BY created_at
`

// 全件取得 (:many は []Author を返す)
func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthorBio = `-- name: UpdateAuthorBio :exec
UPDATE authors SET bio = $2 WHERE id = $1
`

type UpdateAuthorBioParams struct {
	ID  pgtype.UUID
	Bio string
}

// 更新系で戻り値不要な場合は :exec (返り値は error のみ)
func (q *Queries) UpdateAuthorBio(ctx context.Context, arg UpdateAuthorBioParams) error {
	_, err := q.db.Exec(ctx, updateAuthorBio, arg.ID, arg.Bio)
	return err
}
