// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchGetPost = `-- name: BatchGetPost :batchone
SELECT id, author_id, title, body, tags, status, published_at, created_at FROM posts WHERE id = $1
`

type BatchGetPostBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

// :batchone → Batch 内で1行を返すクエリ
// Go 側: .QueryRow(func(i int, p Post, err error){})
func (q *Queries) BatchGetPost(ctx context.Context, id []pgtype.UUID) *BatchGetPostBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchGetPost, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchGetPostBatchResults{br, len(id), false}
}

func (b *BatchGetPostBatchResults) QueryRow(f func(int, Post, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Post
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *BatchGetPostBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertPost = `-- name: BatchInsertPost :batchexec
INSERT INTO posts (author_id, title, body, tags, status)
VALUES ($1, $2, $3, $4, $5)
`

type BatchInsertPostBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertPostParams struct {
	AuthorID pgtype.UUID
	Title    string
	Body     string
	Tags     []string
	Status   PostStatus
}

// :batchexec → pgx の Batch を使って複数行を一括実行
// Go 側: q.BatchInsertPost(ctx, []BatchInsertPostParams{...}).Exec(func(i int, err error){})
func (q *Queries) BatchInsertPost(ctx context.Context, arg []BatchInsertPostParams) *BatchInsertPostBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AuthorID,
			a.Title,
			a.Body,
			a.Tags,
			a.Status,
		}
		batch.Queue(batchInsertPost, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertPostBatchResults{br, len(arg), false}
}

func (b *BatchInsertPostBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertPostBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchListPostsByAuthor = `-- name: BatchListPostsByAuthor :batchmany
SELECT id, author_id, title, body, tags, status, published_at, created_at FROM posts WHERE author_id = $1 ORDER BY created_at
`

type BatchListPostsByAuthorBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

// :batchmany → Batch 内で複数行を返すクエリ
// Go 側: .Query(func(i int, p Post, err error){})
func (q *Queries) BatchListPostsByAuthor(ctx context.Context, authorID []pgtype.UUID) *BatchListPostsByAuthorBatchResults {
	batch := &pgx.Batch{}
	for _, a := range authorID {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchListPostsByAuthor, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchListPostsByAuthorBatchResults{br, len(authorID), false}
}

func (b *BatchListPostsByAuthorBatchResults) Query(f func(int, []Post, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		items := []Post{}
		if b.closed {
			if f != nil {
				f(t, items, ErrBatchAlreadyClosed)
			}
			continue
		}
		err := func() error {
			rows, err := b.br.Query()
			if err != nil {
				return err
			}
			defer rows.Close()
			for rows.Next() {
				var i Post
				if err := rows.Scan(
					&i.ID,
					&i.AuthorID,
					&i.Title,
					&i.Body,
					&i.Tags,
					&i.Status,
					&i.PublishedAt,
					&i.CreatedAt,
				); err != nil {
					return err
				}
				items = append(items, i)
			}
			return rows.Err()
		}()
		if f != nil {
			f(t, items, err)
		}
	}
}

func (b *BatchListPostsByAuthorBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
