// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one

INSERT INTO comments (post_id, body)
VALUES ($1, $2)
RETURNING id, post_id, body, created_at
`

type CreateCommentParams struct {
	PostID pgtype.UUID
	Body   string
}

// 03-relations で使用するクエリ
// 示す機能: 1:N 集約 / LEFT JOIN + COUNT / array_agg
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT id, post_id, body, created_at FROM comments WHERE post_id = $1 ORDER BY created_at
`

func (q *Queries) ListCommentsByPost(ctx context.Context, postID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithCommentBodies = `-- name: ListPostsWithCommentBodies :many
SELECT
    p.id,
    p.title,
    COALESCE(
        array_remove(array_agg(c.body ORDER BY c.created_at), NULL),
        '{}'::text[]
    )::text[] AS comment_bodies
FROM posts p
LEFT JOIN comments c ON c.post_id = p.id
WHERE p.author_id = $1
GROUP BY p.id, p.title
ORDER BY p.created_at
`

type ListPostsWithCommentBodiesRow struct {
	ID            pgtype.UUID
	Title         string
	CommentBodies []string
}

// array_agg() で 1:N の本文を text[] としてまとめる
// FILTER (WHERE ...) で NULL を除外し、COALESCE で空配列を保証する
func (q *Queries) ListPostsWithCommentBodies(ctx context.Context, authorID pgtype.UUID) ([]ListPostsWithCommentBodiesRow, error) {
	rows, err := q.db.Query(ctx, listPostsWithCommentBodies, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsWithCommentBodiesRow{}
	for rows.Next() {
		var i ListPostsWithCommentBodiesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CommentBodies); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithCommentCount = `-- name: ListPostsWithCommentCount :many
SELECT
    p.id,
    p.author_id,
    p.title,
    p.body,
    p.tags,
    p.status,
    p.published_at,
    p.created_at,
    COUNT(c.id)::bigint AS comment_count
FROM posts p
LEFT JOIN comments c ON c.post_id = p.id
WHERE p.author_id = $1
GROUP BY p.id
ORDER BY p.created_at
`

type ListPostsWithCommentCountRow struct {
	ID           pgtype.UUID
	AuthorID     pgtype.UUID
	Title        string
	Body         string
	Tags         []string
	Status       PostStatus
	PublishedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	CommentCount int64
}

// LEFT JOIN + GROUP BY でコメント数を集計する
// COUNT(c.id) はコメントがない投稿では 0 になる
func (q *Queries) ListPostsWithCommentCount(ctx context.Context, authorID pgtype.UUID) ([]ListPostsWithCommentCountRow, error) {
	rows, err := q.db.Query(ctx, listPostsWithCommentCount, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsWithCommentCountRow{}
	for rows.Next() {
		var i ListPostsWithCommentCountRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
