// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.sql

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CopyInsertPostsParams struct {
	AuthorID pgtype.UUID
	Title    string
	Body     string
	Tags     []string
	Status   PostStatus
}
