// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCopyInsertPosts implements pgx.CopyFromSource.
type iteratorForCopyInsertPosts struct {
	rows                 []CopyInsertPostsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyInsertPosts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyInsertPosts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AuthorID,
		r.rows[0].Title,
		r.rows[0].Body,
		r.rows[0].Tags,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForCopyInsertPosts) Err() error {
	return nil
}

// :copyfrom は pgx の CopyFrom プロトコルを使った高速バルク INSERT。
// (:batchexec との違い) batchexec は複数 INSERT を1往復でまとめるが
// copyfrom は PostgreSQL COPY プロトコルを使うためさらに高速。
// 戻り値は挿入件数 (int64)。
func (q *Queries) CopyInsertPosts(ctx context.Context, arg []CopyInsertPostsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"posts"}, []string{"author_id", "title", "body", "tags", "status"}, &iteratorForCopyInsertPosts{rows: arg})
}
