// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fulltext.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchPostsFullText = `-- name: SearchPostsFullText :many
SELECT
    id,
    title,
    body,
    ts_rank(
        to_tsvector('simple', title || ' ' || body),
        plainto_tsquery('simple', $1)
    ) AS rank
FROM posts
WHERE to_tsvector('simple', title || ' ' || body)
      @@ plainto_tsquery('simple', $1)
ORDER BY rank DESC
LIMIT $2
`

type SearchPostsFullTextParams struct {
	PlaintoTsquery string
	Limit          int32
}

type SearchPostsFullTextRow struct {
	ID    pgtype.UUID
	Title string
	Body  string
	Rank  float32
}

// to_tsvector('simple', ...) @@ plainto_tsquery('simple', ...) で全文検索。
// 'simple' 辞書は形態素解析なしで英数字をそのまま正規化する。
// ts_rank() でスコア降順に並べる。
// idx_posts_search (GIN) が WHERE 節で使われて高速化される。
func (q *Queries) SearchPostsFullText(ctx context.Context, arg SearchPostsFullTextParams) ([]SearchPostsFullTextRow, error) {
	rows, err := q.db.Query(ctx, searchPostsFullText, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsFullTextRow{}
	for rows.Next() {
		var i SearchPostsFullTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
