// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus
	Valid      bool // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type Author struct {
	ID        pgtype.UUID
	Name      string
	Bio       string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type Comment struct {
	ID        pgtype.UUID
	PostID    pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID          pgtype.UUID
	AuthorID    pgtype.UUID
	Title       string
	Body        string
	Tags        []string
	Status      PostStatus
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}
