// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one

INSERT INTO posts (author_id, title, body, tags, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, title, body, tags, status, published_at, created_at
`

type CreatePostParams struct {
	AuthorID pgtype.UUID
	Title    string
	Body     string
	Tags     []string
	Status   PostStatus
}

// 02-transactions / 03-relations / 05-batch で使用するクエリ
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Tags,
		arg.Status,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Tags,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT p.id, p.author_id, p.title, p.body, p.tags, p.status, p.published_at, p.created_at, a.id, a.name, a.bio, a.metadata, a.created_at
FROM posts p
JOIN authors a ON a.id = p.author_id
WHERE p.id = $1
`

type GetPostWithAuthorRow struct {
	Post   Post
	Author Author
}

// sqlc.embed() を使った JOIN
// 生成される行型: GetPostWithAuthorRow { Post Post; Author Author }
// p.* や a.* ではなく sqlc.embed() を使うことでカラム名衝突を回避する
func (q *Queries) GetPostWithAuthor(ctx context.Context, id pgtype.UUID) (GetPostWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getPostWithAuthor, id)
	var i GetPostWithAuthorRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.Tags,
		&i.Post.Status,
		&i.Post.PublishedAt,
		&i.Post.CreatedAt,
		&i.Author.ID,
		&i.Author.Name,
		&i.Author.Bio,
		&i.Author.Metadata,
		&i.Author.CreatedAt,
	)
	return i, err
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT id, author_id, title, body, tags, status, published_at, created_at FROM posts WHERE author_id = $1 ORDER BY created_at
`

func (q *Queries) ListPostsByAuthor(ctx context.Context, authorID pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
