// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts_dynamic.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPostsByIDs = `-- name: ListPostsByIDs :many
SELECT id, author_id, title, body, tags, status, published_at, created_at FROM posts WHERE id = ANY($1::uuid[])
`

// sqlc.slice('x') → pgx/v5 では WHERE id = ANY($1::uuid[]) に展開される
// Go 側の引数は []pgtype.UUID になる (IN ($1,$2,...) ではない点に注意)
func (q *Queries) ListPostsByIDs(ctx context.Context, ids []pgtype.UUID) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPosts = `-- name: SearchPosts :many

SELECT id, author_id, title, body, tags, status, published_at, created_at FROM posts
WHERE
    ($1::uuid IS NULL OR author_id = $1::uuid)
    AND ($2::post_status IS NULL OR status = $2::post_status)
    AND ($3::text IS NULL OR title ILIKE $3::text)
ORDER BY created_at DESC
LIMIT $4::bigint
`

type SearchPostsParams struct {
	AuthorID   pgtype.UUID
	Status     NullPostStatus
	TitleLike  pgtype.Text
	LimitCount int64
}

// 04-dynamic で使用するクエリ
// 示す機能: sqlc.arg() / sqlc.narg() / sqlc.slice()
// sqlc.narg('x') → NULL 許容引数を生成する (NullXxx 型)
// IS NULL OR col = $x パターンで動的フィルタを実現する
func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.AuthorID,
		arg.Status,
		arg.TitleLike,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Tags,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostFlexible = `-- name: UpdatePostFlexible :exec
UPDATE posts
SET
    title  = COALESCE($1::text, title),
    status = COALESCE($2::post_status, status)
WHERE id = $3::uuid
`

type UpdatePostFlexibleParams struct {
	Title  pgtype.Text
	Status NullPostStatus
	ID     pgtype.UUID
}

// sqlc.narg() + COALESCE パターンで部分更新を実現する
// NULL を渡した列は元の値を維持する
func (q *Queries) UpdatePostFlexible(ctx context.Context, arg UpdatePostFlexibleParams) error {
	_, err := q.db.Exec(ctx, updatePostFlexible, arg.Title, arg.Status, arg.ID)
	return err
}
