// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// text[] 列に要素を追加する (array_cat)
	// Go 側の引数 new_tags は []string になる (pgx/v5 + emit_empty_slices)
	AddPostTags(ctx context.Context, arg AddPostTagsParams) error
	// :batchone → Batch 内で1行を返すクエリ
	// Go 側: .QueryRow(func(i int, p Post, err error){})
	BatchGetPost(ctx context.Context, id []pgtype.UUID) *BatchGetPostBatchResults
	// :batchexec → pgx の Batch を使って複数行を一括実行
	// Go 側: q.BatchInsertPost(ctx, []BatchInsertPostParams{...}).Exec(func(i int, err error){})
	BatchInsertPost(ctx context.Context, arg []BatchInsertPostParams) *BatchInsertPostBatchResults
	// :batchmany → Batch 内で複数行を返すクエリ
	// Go 側: .Query(func(i int, p Post, err error){})
	BatchListPostsByAuthor(ctx context.Context, authorID []pgtype.UUID) *BatchListPostsByAuthorBatchResults
	// 01-basics で使用するクエリ
	// 示す機能: :one / :many / :exec / :execrows
	// INSERT ... RETURNING * → Author 構造体を返す (:one)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	// 03-relations で使用するクエリ
	// 示す機能: 1:N 集約 / LEFT JOIN + COUNT / array_agg
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	// 02-transactions / 03-relations / 05-batch で使用するクエリ
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	// :execrows は影響を受けた行数を int64 で返す
	// 例: 0 なら対象なし、1 なら削除成功
	DeleteAuthor(ctx context.Context, id pgtype.UUID) (int64, error)
	// 主キーで1行取得 (:one は存在しない場合 pgx.ErrNoRows を返す)
	GetAuthor(ctx context.Context, id pgtype.UUID) (Author, error)
	// jsonb カラムを読み返して []byte として受け取る
	GetAuthorMetadata(ctx context.Context, id pgtype.UUID) ([]byte, error)
	// text[] を []string として受け取る
	GetPostTags(ctx context.Context, id pgtype.UUID) ([]string, error)
	// sqlc.embed() を使った JOIN
	// 生成される行型: GetPostWithAuthorRow { Post Post; Author Author }
	// p.* や a.* ではなく sqlc.embed() を使うことでカラム名衝突を回避する
	GetPostWithAuthor(ctx context.Context, id pgtype.UUID) (GetPostWithAuthorRow, error)
	// CTE を使った keyset ページネーション
	// cursor_id が NULL の場合は先頭ページ、指定した場合はその投稿の次ページを返す
	// インデックス idx_posts_keyset (created_at DESC, id DESC) を活用する
	KeysetListPosts(ctx context.Context, arg KeysetListPostsParams) ([]Post, error)
	// 全件取得 (:many は []Author を返す)
	ListAuthors(ctx context.Context) ([]Author, error)
	ListCommentsByPost(ctx context.Context, postID pgtype.UUID) ([]Comment, error)
	ListPostsByAuthor(ctx context.Context, authorID pgtype.UUID) ([]Post, error)
	// sqlc.slice('x') → pgx/v5 では WHERE id = ANY($1::uuid[]) に展開される
	// Go 側の引数は []pgtype.UUID になる (IN ($1,$2,...) ではない点に注意)
	ListPostsByIDs(ctx context.Context, ids []pgtype.UUID) ([]Post, error)
	// array_agg() で 1:N の本文を text[] としてまとめる
	// FILTER (WHERE ...) で NULL を除外し、COALESCE で空配列を保証する
	ListPostsWithCommentBodies(ctx context.Context, authorID pgtype.UUID) ([]ListPostsWithCommentBodiesRow, error)
	// LEFT JOIN + GROUP BY でコメント数を集計する
	// COUNT(c.id) はコメントがない投稿では 0 になる
	ListPostsWithCommentCount(ctx context.Context, authorID pgtype.UUID) ([]ListPostsWithCommentCountRow, error)
	// PostStatus 型の定数 (PostStatusPublished 等) を使う例
	ListPublishedPosts(ctx context.Context) ([]Post, error)
	// 04-dynamic で使用するクエリ
	// 示す機能: sqlc.arg() / sqlc.narg() / sqlc.slice()
	// sqlc.narg('x') → NULL 許容引数を生成する (NullXxx 型)
	// IS NULL OR col = $x パターンで動的フィルタを実現する
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error)
	// 更新系で戻り値不要な場合は :exec (返り値は error のみ)
	UpdateAuthorBio(ctx context.Context, arg UpdateAuthorBioParams) error
	// sqlc.narg() + COALESCE パターンで部分更新を実現する
	// NULL を渡した列は元の値を維持する
	UpdatePostFlexible(ctx context.Context, arg UpdatePostFlexibleParams) error
	// 06-advanced で使用するクエリ
	// 示す機能: JSONB / text[] 配列 / CTE + keyset ページネーション / enum 値
	// jsonb 列に []byte (JSON) を渡す
	// sqlcgen 側の型: []byte (pgx/v5 のデフォルト)
	UpsertAuthorMetadata(ctx context.Context, arg UpsertAuthorMetadataParams) error
}

var _ Querier = (*Queries)(nil)
