// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuthorIgnoreConflict = `-- name: InsertAuthorIgnoreConflict :execrows
INSERT INTO authors (name, bio, metadata, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO NOTHING
`

type InsertAuthorIgnoreConflictParams struct {
	Name     string
	Bio      string
	Metadata []byte
	Email    pgtype.Text
}

// 同じ email が既に存在する場合は何もせず 0 行を返す。
// 戻り値 (int64) で挿入されたか衝突したかを判別できる。
func (q *Queries) InsertAuthorIgnoreConflict(ctx context.Context, arg InsertAuthorIgnoreConflictParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAuthorIgnoreConflict,
		arg.Name,
		arg.Bio,
		arg.Metadata,
		arg.Email,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAuthorByEmail = `-- name: UpsertAuthorByEmail :one
INSERT INTO authors (name, bio, metadata, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO UPDATE
  SET name     = EXCLUDED.name,
      bio      = EXCLUDED.bio,
      metadata = EXCLUDED.metadata
RETURNING id, name, bio, metadata, created_at, email
`

type UpsertAuthorByEmailParams struct {
	Name     string
	Bio      string
	Metadata []byte
	Email    pgtype.Text
}

// 同じ email が既に存在する場合は name / bio / metadata を更新して返す。
// EXCLUDED.* は INSERT しようとした新しい値を参照する。
func (q *Queries) UpsertAuthorByEmail(ctx context.Context, arg UpsertAuthorByEmailParams) (Author, error) {
	row := q.db.QueryRow(ctx, upsertAuthorByEmail,
		arg.Name,
		arg.Bio,
		arg.Metadata,
		arg.Email,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}
