// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: window.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPostsPageWithTotal = `-- name: ListPostsPageWithTotal :many
SELECT
    id,
    title,
    created_at,
    COUNT(*) OVER() AS total_count
FROM posts
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListPostsPageWithTotalParams struct {
	Limit  int32
	Offset int32
}

type ListPostsPageWithTotalRow struct {
	ID         pgtype.UUID
	Title      string
	CreatedAt  pgtype.Timestamptz
	TotalCount int64
}

// COUNT(*) OVER() で全件数を取得しながら LIMIT/OFFSET でページング。
// 1 クエリで total_count とページ内容を同時に取得できる。
func (q *Queries) ListPostsPageWithTotal(ctx context.Context, arg ListPostsPageWithTotalParams) ([]ListPostsPageWithTotalRow, error) {
	rows, err := q.db.Query(ctx, listPostsPageWithTotal, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsPageWithTotalRow{}
	for rows.Next() {
		var i ListPostsPageWithTotalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsRankedByAuthor = `-- name: ListPostsRankedByAuthor :many
SELECT
    id,
    author_id,
    title,
    created_at,
    ROW_NUMBER() OVER (PARTITION BY author_id ORDER BY created_at DESC) AS row_num
FROM posts
ORDER BY author_id, row_num
`

type ListPostsRankedByAuthorRow struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
	RowNum    int64
}

// ROW_NUMBER() OVER (PARTITION BY ...) で著者ごとの新着順番号を付与する。
// PARTITION BY で著者ごとにリセット、ORDER BY created_at DESC で新しい投稿が 1 番。
func (q *Queries) ListPostsRankedByAuthor(ctx context.Context) ([]ListPostsRankedByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listPostsRankedByAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRankedByAuthorRow{}
	for rows.Next() {
		var i ListPostsRankedByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.CreatedAt,
			&i.RowNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsWithPrevTitle = `-- name: ListPostsWithPrevTitle :many
SELECT
    id,
    author_id,
    title,
    created_at,
    LAG(title) OVER (PARTITION BY author_id ORDER BY created_at) AS prev_title
FROM posts
ORDER BY author_id, created_at
`

type ListPostsWithPrevTitleRow struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	Title     string
	CreatedAt pgtype.Timestamptz
	PrevTitle interface{}
}

// LAG() OVER (...) で同一著者の1つ前の投稿タイトルを取得する。
// 先頭行の prev_title は NULL (pgtype.Text{Valid: false}) になる。
func (q *Queries) ListPostsWithPrevTitle(ctx context.Context) ([]ListPostsWithPrevTitleRow, error) {
	rows, err := q.db.Query(ctx, listPostsWithPrevTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsWithPrevTitleRow{}
	for rows.Next() {
		var i ListPostsWithPrevTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.CreatedAt,
			&i.PrevTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
